# Generated by Django 4.0.5 on 2022-06-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
