# Generated by Django 4.0.5 on 2022-06-20 12:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0003_alter_profile_image_alter_project_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default.png', max_length=255, verbose_name='image'),
        ),
    ]
